services:
  - type: web
    name: aoc2025
    env: python
    buildCommand: "./build.sh"
    startCommand: "uv run gunicorn --chdir src/aoc2025/web --bind 0.0.0.0:$PORT --workers 2 aoc2025.web.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: AOC_SESSION_COOKIE
        sync: false  # Set this manually in Render dashboard
      - key: ALLOWED_HOSTS
        sync: false  # Set to your render domain
